"""Behaviour: compiling the catalog (TOOLS) and the constraint registry of an instance.

A `tools:` front matter proposes names; this module is where a name resolves to what
it's FOR. The full contract of a given proc comes with the block instead, the day it is
actually CALLed -- TOOLS is a menu, not the dish.
"""
from __future__ import annotations

import re
from pathlib import Path

from .. import reading
from ..state import instance
from ..core.errors import Refusal
from ..core import language
from ..core.model import Constraint, Tool
from . import contributions, topology

STATE_PARTS = tuple(Path(instance.STATE).parts)
VENDOR_PARTS = tuple(Path(instance.VENDOR).parts)
BORDER = "---"
TAG = re.compile(r"@([A-Za-z0-9_-]+)\.([A-Za-z0-9_-]+)")

RESERVED = tuple(sorted(contributions.SYSTEM_VERBS))   # ONE list: the contract reserves them
PLAYED = ("proc", "boot")   # the kinds whose `proc:` the engine PLAYS -- a flow lives at
                            # either; read here, judged here, said once
# the console's own verbs: the dispatch resolves them BEFORE the skills, so a
# skill under one of these names is unreachable through `pp <name>` -- lint says so


def _swept(meta: Path):
    """-> every reachable document of the WHOLE composition, the switches ignored:
    what the registry, the attaches and the lint judge -- off is not gone, and a
    code doubled by a switched package must still refuse when it comes back. The
    machine's run state is not a document, `_`-prefixed working files are never
    scanned, and a vendored package's `user/` copies are REFERENCE material (the
    PLACED instance files are the live ones -- sweeping both would double every
    declaration). The catalog reads `_played` instead."""
    for path in sorted(meta.rglob("*.md")):
        parts = path.relative_to(meta).parts
        if parts[:len(STATE_PARTS)] == STATE_PARTS or path.name.startswith("_"):
            continue
        if parts[:len(VENDOR_PARTS)] == VENDOR_PARTS and len(parts) > 3 and parts[3] == "user":
            continue
        yield path


def _played(meta: Path):
    """-> the documents IN PLAY: `_swept` without the vendored packages the switches
    take out (`instance.vendored(meta)`, the same composition every other reader of
    the play sees) -- what the catalog compiles from, so a switched package leaves
    no line in what the agent reads."""
    playing = {root.name for root in instance.vendored(meta)}
    for path in _swept(meta):
        parts = path.relative_to(meta).parts
        if parts[:len(VENDOR_PARTS)] == VENDOR_PARTS and parts[len(VENDOR_PARTS)] not in playing:
            continue
        yield path
HEADER = """---
name: tools
description: >-
  The catalog: every tool this instance carries, name and description alone. A proc's
  full contract reaches the block only when it is CALLed.
kind: doc
generated: pp build
---

[GENERATED by `pp build` -- do not edit; the source is each package, proc and skill]

# The TOOLS of this instance

ONE kind lives here: the SKILL, the same form your harness uses. pp plays every
offered name: a `proc:` is conducted, a script runs under the skill's own laws, a
bare contract opens as a step (its body is the brief, the work is yours).
Registering one at your harness changes nothing for pp.

A contract line is an ADDRESS: the name resolves through the instance's search
paths -- serve rows, mounts and CALLs use it as is, and an upgrade never moves
it. A vendored path (`.sys/vendor/<package>@<version>/...`) is a PIN: never
write one into a document.
"""


def front_matter_of(path: Path) -> str | None:
    """-> the raw front matter text, or None when the file carries none."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != BORDER:
        return None
    end = next((i for i, line in enumerate(lines[1:], 1) if line.strip() == BORDER), None)
    return "\n".join(lines[1:end]) if end else None


def _front(path: Path) -> dict[str, str] | None:
    raw = front_matter_of(path)
    return reading.front_matter(raw.splitlines()) if raw is not None else None


def _package_entries(root: Path) -> list[tuple[str, dict[str, str] | None, Path]]:
    """-> (name, front, contract) for one package: its procs, then its skills.
    `_` files are shelf ideas -- never scanned, nowhere."""
    procs = [(path.stem, _front(path), path) for path in sorted((root / "procs").glob("*.md"))
             if not path.name.startswith("_")]
    skills = [(path.parent.name, _front(path), path)
              for path in sorted((root / "skills").glob("*/SKILL.md"))]
    return procs + skills


def _instance_entries(meta: Path) -> list[tuple[str, dict[str, str] | None, Path]]:
    """-> the instance's OWN space: top-level procs, the user's `procs/` AND its
    `skills/` -- ONE kind of registered element, however it is shelved."""
    top = [(path.stem, front, path) for path in sorted(meta.glob("*.md"))
           if (front := _front(path)) and front.get("kind") in PLAYED]
    user = [(path.stem, _front(path), path) for path in sorted((meta / "procs").glob("*.md"))
            if not path.name.startswith("_")]
    own_skills = [(path.parent.name, _front(path), path)
                  for path in sorted((meta / "skills").glob("*/SKILL.md"))]
    return top + user + own_skills


def entries(meta: Path) -> list[tuple[str, dict[str, str] | None, Path]]:
    found = _instance_entries(meta)
    for root in instance.vendored(meta):
        found += _package_entries(root)
    return found


def _sources(meta: Path, roots: list[Path]) -> list[tuple[str, Path]]:
    """-> (name, contract) for every proc and skill of the instance's own space, then
    of each root given -- the one listing both resolutions walk."""
    sources = ([(path.stem, path) for path in sorted(meta.glob("*.md"))]
               + [(path.stem, path) for path in sorted((meta / "procs").glob("*.md"))]
               + [(path.parent.name, path) for path in sorted((meta / "skills").glob("*/SKILL.md"))])
    for root in roots:
        sources += [(path.stem, path) for path in sorted((root / "procs").glob("*.md"))]
        sources += [(path.parent.name, path) for path in sorted((root / "skills").glob("*/SKILL.md"))]
    return sources


def _located(meta: Path, name: str) -> tuple[str, Path]:
    """-> (what `name` is FOR, where its contract lives) among what PLAYS -- the
    instance's own space and `instance.vendored(meta)` -- by identity, never guessed."""
    for candidate, path in _sources(meta, instance.vendored(meta)):
        front = _front(path)
        if candidate == name and front and front.get("description"):
            return front["description"], path
    raise Refusal("unknown-tool", f"`{name}` -- nothing under {meta} carries that name")


def _owned(meta: Path, name: str) -> Path | None:
    """-> where `name` lives in the WHOLE composition -- the instance's own space, then
    every pinned package, switched off included (`switched=False`) -- or None when
    nothing pp composes carries it. Who OWNS a name, whatever plays; no description
    read: a name owned by a switched package is neither offered nor left to the
    harness, and only a name nobody owns is the harness's."""
    for candidate, path in _sources(meta, instance.vendored(meta, switched=False)):
        if candidate == name:
            return path
    return None


def describe(meta: Path, name: str) -> str:
    return _located(meta, name)[0]


def conductible(contract: Path) -> str:
    """-> "" when pp can CONDUCT this contract (a readable front matter, a
    `description:`), the lack named otherwise -- the
    one verdict the dispatch, the offers and the lint share."""
    try:
        front = _front(contract)
    except Refusal:
        return "its front matter is not valid YAML"
    if front is None:
        return "it carries no front matter"
    if not front.get("description"):
        return "it declares no `description:`"
    return ""


def _adopted_tool(meta: Path, name: str) -> Tool | None:
    """-> the Tool an OFFERED name resolves to at a harness home -- full (description
    and contract) only when pp can conduct it; None otherwise (found-but-incompatible
    stays a name-only offer: indifferent, the lint says why)."""
    if not instance.is_instance(meta):
        return None
    contract = instance.adopted(meta, name)
    if contract is None or conductible(contract):
        return None
    front = _front(contract) or {}
    return Tool(name=name, description=str(front.get("description", "")),
                contract=str(contract))


def tools_of(document, meta: Path | None = None) -> tuple[Tool, ...]:
    """-> the `tools:` a document proposes -- description AND contract path: what is
    handed to the agent's free will must be readable in full. A PACKAGE document
    resolves them in its own package first (its skills travel with it); a name a
    switched package owns is DROPPED from the offer (that package renders nothing);
    an OFFERED name nothing pp composes owns may be ADOPTED from a harness home."""
    names = reading.tool_names(document)
    if not names:
        return ()
    package = instance.package_of(document.path)
    base = meta if meta is not None else document.path.parent
    found = []
    for name in names:
        contract = (package / "skills" / name / "SKILL.md") if package else None
        if contract and contract.is_file():
            front = _front(contract) or {}
            found.append(Tool(name=name, description=front.get("description", ""),
                              contract=str(contract)))
        else:
            try:
                description, path = _located(base, name)
                found.append(Tool(name=name, description=description, contract=str(path)))
            except Refusal:
                if _owned(base, name) is not None:
                    continue         # owned by a package out of the play: not offered
                found.append(_adopted_tool(base, name)
                             or Tool(name=name, description="", contract=""))
                # adopted when a harness home holds a conductible contract; otherwise
                # declared to the HARNESS: pp offers and scopes it, the harness runs it
    return tuple(found)


def _resolve_tags(meta: Path, text: str) -> str:
    """-> `text` with every `@Doc.field` replaced by that document's own front matter
    value -- one pass, no re-scan of what a substitution produced: nothing to cycle on.
    A tag that resolves to nothing REFUSES: a constraint referencing an absent field is
    a lie, not a blank."""
    def substitute(match: re.Match) -> str:
        stem, field = match.group(1), match.group(2)
        path = instance.resolve(meta, f"{stem}.md")
        value = reading.read(path).front.get(field, "") if path.is_file() else ""
        if value == "" or value is None:
            raise Refusal("tag-unresolved", f"`@{stem}.{field}` -- no `{field}:` on `{stem}.md`")
        return str(value)
    return TAG.sub(substitute, text)


def effective(meta: Path, document) -> tuple[tuple[Constraint, ...], tuple[Tool, ...]]:
    """-> the constraints and tools a frame on `document` puts in force: the base's
    sections, then each overlay's DELTAS -- adding what is already there, or removing
    what is not, refuses: a silent no-op delta is a lie."""
    laws = list(reading.constraints(document))
    tools = list(tools_of(document, meta))
    for overlay_path in instance.overlays_of(meta, document.path.name):
        overlay = reading.read(overlay_path)
        if overlay.front.get("proc"):
            raise Refusal("overlay-carries-proc",
                          f"{overlay_path} overlays {document.path.name} and declares a "
                          "`proc:` -- flow extends through HOOK/attach, never a shadow")
        reading.overlay_serve_lines(overlay)    # a `-` serve row refuses here, by name
        for sign, code, text, section in reading.constraint_deltas(overlay):
            held = {one.code for one in laws}
            if sign == "-" and code not in held:
                raise Refusal("overlay-removes-nothing",
                              f"{overlay_path.name}: `-{code}` -- not in force here")
            if sign == "+" and code in held:
                raise Refusal("overlay-adds-existing",
                              f"{overlay_path.name}: `+{code}` -- already in force")
            laws = ([one for one in laws if one.code != code] if sign == "-"
                    else laws + [Constraint(code=code, text=text, section=section)])
        for sign, name in reading.tool_deltas(overlay):
            offered = {one.name for one in tools}
            if sign == "-" and name not in offered:
                raise Refusal("overlay-removes-nothing",
                              f"{overlay_path.name}: `-{name}` -- not offered here")
            if sign == "+" and name in offered:
                raise Refusal("overlay-adds-existing",
                              f"{overlay_path.name}: `+{name}` -- already offered")
            if sign == "-":
                tools = [one for one in tools if one.name != name]
            else:
                try:
                    description, path = _located(meta, name)
                    tools = tools + [Tool(name=name, description=description,
                                          contract=str(path))]
                except Refusal:
                    if _owned(meta, name) is not None:
                        continue     # owned by a package out of the play: not offered
                    tools = tools + [_adopted_tool(meta, name)
                                     or Tool(name=name, description="", contract="")]
    laws = [Constraint(code=one.code, text=_resolve_tags(meta, one.text), section=one.section)
            for one in laws]
    return tuple(laws), tuple(tools)


def format_enumeration(meta: Path) -> dict[str, tuple[str, str, str]]:
    """-> name -> (mode, definition, holder). Three LEVELS: the engine's builtins,
    the vendored packages IN PLAY, the instance's OWN space -- a nearer level
    OVERRIDES a name (customizing is redeclaring at home, never editing a bundle); a
    name declared twice WITHIN one level refuses: there, a format has ONE owner. A
    switched package declares no format: nothing in play could name it."""
    from ..core import language
    engine_tier = {name: (mode, definition, "engine")
                   for name, (mode, definition) in language.FORMATS.items()}
    package_tier: dict[str, tuple[str, str, str]] = {}
    own_tier: dict[str, tuple[str, str, str]] = {}
    for path in _played(meta):
        try:
            document = reading.read(path)
        except Refusal as refusal:
            if refusal.code.startswith("front-matter"):
                continue
            raise
        relative = path.relative_to(meta)
        where = str(relative)
        tier = (package_tier if relative.parts[:len(VENDOR_PARTS)] == VENDOR_PARTS
                else own_tier)
        for name, mode, definition in reading.formats(document):
            if name in tier:
                raise Refusal("format-doubled",
                              f"`{name}` is already owned by {tier[name][2]}")
            tier[name] = (mode, definition, where)
    return {**engine_tier, **package_tier, **own_tier}


def _declared_names(meta: Path) -> list[str]:
    """-> every `tools:` name declared by a reachable document that NOTHING pp composes
    owns -- resolved against the WHOLE composition, so a name a switched package owns
    is neither here nor anywhere in the catalog: the candidates for adoption, and the
    names truly left to the harness."""
    named = set()
    for path in _swept(meta):
        front = _front(path)
        if front is None:
            continue
        for token in str(front.get("tools", "")).split():
            if not token.startswith("-"):
                named.add(token.removeprefix("+"))
    unresolved = []
    for name in sorted(named):
        try:
            _located(meta, name)
        except Refusal:
            if _owned(meta, name) is None:
                unresolved.append(name)
    return unresolved


def _adopted_offers(meta: Path) -> list[tuple[str, str, Path]]:
    """-> (name, description, contract) for every offered name ADOPTED from a harness
    home -- conductible contracts only; the offer is the consent that lets pp read them."""
    found = []
    for name in _declared_names(meta):
        tool = _adopted_tool(meta, name)
        if tool is not None:
            found.append((name, tool.description, Path(tool.contract)))
    return found


def _declared_harness(meta: Path) -> list[str]:
    """-> the offered names left to the HARNESS alone: declared, owned by nothing pp
    composes, and not adopted -- pp offers and scopes them by name and has not read
    them; the harness holds their description and runs them."""
    taken = {name for name, _, _ in _adopted_offers(meta)}
    return [name for name in _declared_names(meta) if name not in taken]


def render_tools(meta: Path) -> str:
    """-> the compiled catalog. Same entries in, same bytes out."""
    own = entries(meta)
    if not own:
        raise Refusal("no-tools", f"no package, proc or skill under {meta}")
    body = HEADER + "\n" + _listed(own)
    enumeration = format_enumeration(meta)
    body += ("\n## The OUTPUT formats\n\nWhat a block's OUTPUT may name -- the form "
             "your production takes, and how it travels (`inline` on the call, `stdin` "
             "piped):\n\n"
             + "".join(f"- **`{name}`** ({mode}) — {definition}\n"
                       for name, (mode, definition, _) in sorted(enumeration.items())))
    taken = _adopted_offers(meta)
    if taken:
        body += ("\n## Adopted skills (offered from your harness)\n\n"
                 "Named by this instance's `tools:`, found at a harness home -- pp "
                 "conducts them like any skill of the instance (their constraints in "
                 "force while they play):\n\n"
                 + "".join(f"- **`{name}`** — {description}\n  contract: {contract}\n"
                           for name, description, contract in taken))
    declared = _declared_harness(meta)
    if declared:
        body += ("\n## Harness skills (declared)\n\n"
                 "Named by this instance's `tools:` and owned by nothing pp composes -- pp "
                 "offers and scopes them by name; it has not read them: your harness holds "
                 "their description and runs them:\n\n"
                 + "".join(f"- `{name}`\n" for name in declared))
    contributed = contributions.composed(meta)
    if contributed:
        # the packages' CONTRIBUTIONS, as declared -- the catalog says where each
        # package plugs into the engine; absent declarations, no section at all
        body += ("\n## The CONTRIBUTIONS\n\nWhat the packages declare under `contributes:` "
                 "-- the point each one plugs into, in the requires topology:\n\n"
                 + "".join(f"- **`{one['package']}`** {one['kind']}: " + _said(one) + "\n"
                           for one in contributed))
    dropped = [name for name, front, _ in own if not front or not front.get("description")]
    if dropped:      # a shortcut never lies: say what carries no description
        body += ("\n## Undescribed\n\nNothing to say about: "
                 f"{', '.join(f'`{name}`' for name in sorted(set(dropped)))}.\n")
    return f"{body}\n"


def _listed(found: list[tuple[str, dict[str, str] | None, Path]]) -> str:
    """The catalog line carries the contract's ADDRESS -- the name that RESOLVES
    through the instance's search paths (a skill by its bare name, a document by
    `<name>.md`), never the vendored path: a version-pinned path copied into a
    row dies at the next upgrade."""
    return "".join(
        f"- **`{name}`** — {front['description']}\n  contract: "
        + (name if path.name == "SKILL.md" else f"{name}.md") + "\n"
        for name, front, path in found if front and front.get("description"))


RECEIPTS = "receipts.yaml"


def receipt_inputs(meta: Path) -> str:
    """-> ONE digest over every compilation input of the marble, path-ordered: the
    vendored system fragments and the kit's canonical card, over the WHOLE
    composition -- a switch moves nothing here, it moves `switch_state`. What a
    build receipt records, and what a boot recomputes to tell a current artifact
    from a stale one."""
    import hashlib
    digest = hashlib.sha256()
    for root in instance.vendored(meta, switched=False):
        for path in sorted((root / "system").glob("*.md")):
            digest.update(str(path.relative_to(meta)).encode("utf-8"))
            digest.update(path.read_bytes())
        card = root / "refs" / "PP.md"
        if root.name.startswith(f"{instance.base_of(meta)}@") and card.is_file():
            digest.update(str(card.relative_to(meta)).encode("utf-8"))
            digest.update(card.read_bytes())
    return digest.hexdigest()


def catalog_inputs(meta: Path) -> str:
    """-> ONE digest over the INSTANCE's side of the catalog's inputs, path-ordered: the
    member, the formats, the overlay procs and the instance's own skills. The vendored
    side is pinned by version and needs no digest.

    documentary: the receipt says what the catalog was read from; a boot that finds the
    digest moved recompiles before it serves -- what you read is what plays
    (le-recu-du-catalogue)."""
    import hashlib
    digest = hashlib.sha256()
    paths = [meta / "MEMBER.md", meta / "FORMATS.md"]
    if (meta / "procs").is_dir():
        paths += sorted((meta / "procs").glob("*.md"))
    if (meta / "skills").is_dir():
        paths += sorted((meta / "skills").glob("*/SKILL.md"))
    for path in paths:
        if path.is_file():
            digest.update(str(path.relative_to(meta)).encode("utf-8"))
            digest.update(path.read_bytes())
    return digest.hexdigest()


def switch_state(meta: Path) -> str:
    """-> the packages SETTINGS switches off, sorted and joined -- what the marble and
    the catalog were compiled without; a boot that finds it moved recompiles both."""
    return ",".join(sorted(instance.hard_off(meta)))


def receipts(meta: Path) -> dict:
    """The build receipts: artifact name -> {engine, inputs} of its LAST compile.
    Machine-owned; what lets a boot refuse a stale artifact instead of serving it."""
    path = meta / instance.SYS / RECEIPTS
    if not path.is_file():
        return {}
    import yaml
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    return loaded if isinstance(loaded, dict) else {}


def _record_receipt(meta: Path, artifact: Path) -> None:
    """One receipt per compiled artifact: which engine compiled it, from which
    inputs -- the `projections.yaml` motif turned inward. A call that compiles
    without leaving a receipt cannot happen anymore: the builders all pass here."""
    import yaml
    from ..core.version import VERSION
    held = receipts(meta)
    held[artifact.name] = {"engine": VERSION, "inputs": receipt_inputs(meta),
                           "catalog": catalog_inputs(meta), "switches": switch_state(meta)}
    path = meta / instance.SYS / RECEIPTS
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(held, sort_keys=True), encoding="utf-8")


def _said(contribution: dict) -> str:
    """-> one contribution on one line: a data kind by its names, an executed one
    by its fields."""
    value = contribution.get("value")
    if value is not None:
        if isinstance(value, (list, tuple)):
            return ", ".join(str(one) for one in value)
        if isinstance(value, dict):
            return ", ".join(f"{key}: {', '.join(map(str, inner))}" if isinstance(inner, (list, dict))
                             else f"{key}: {inner}" for key, inner in value.items())
        return str(value)
    return ", ".join(f"{key}={val}" for key, val in contribution.items()
                     if key not in ("package", "kind"))


def build_tools(meta: Path) -> Path:
    from . import events
    topology.validate(meta)        # the contract's gate, whole: an invalid declaration or
    events.families(meta)          # the vector registry validated WHOLE: a family one provider
                                   # guards and nobody verifies refuses here, by name
    path = meta / instance.SYS / "tools.md"   # an undeclared dependency refuses here, by
                                              # name, before anything is written
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_tools(meta), encoding="utf-8")
    _record_receipt(meta, path)
    return path


REGISTRY = """# The CONSTRAINT registry — a working document

[GENERATED by `pp build` -- do not edit; never served to an agent]

> A constraint has ONE holder: the document that carries its TEXT. This registry
> serves deduplication and maintenance; the constraints in force travel VERBATIM
> in every block -- a code alone means nothing twenty turns later.

| Code | Section | Holder | Statement |
|---|---|---|---|
"""


def authored(meta: Path, holder: str) -> bool:
    """-> whether `holder` is a document of the AUTHOR rather than of a package.
    `instance.package_of` names the package a file belongs to and renders None when
    none does: the instance's own documents and the adopted harness skills. THE one
    place the judgment is made -- the core stays blind to it."""
    return instance.package_of((meta / holder).resolve()) is None


def _deltas(meta: Path, document, shown: str, warnings: list[str]) -> list[tuple[str, str, str, str]]:
    """-> the document's law deltas. The parser stays strict: a malformed line refuses.
    A PACKAGE's document refuses with it; the AUTHOR's is played WITHOUT that line, and
    the line is named at `warnings` -- a law the author wrote never blocks the build."""
    try:
        return reading.constraint_deltas(document)
    except Refusal as refusal:
        if refusal.code != "constraint-malformed" or not authored(meta, shown):
            raise
    found = []
    for key, section in reading.SECTIONS:
        for line in reading.law_lines(document, key):
            try:
                found.append(reading.constraint_delta(line, section))
            except Refusal as refusal:
                warnings.append(f"constraint-malformed: `{shown}` plays WITHOUT one law -- "
                                f"{str(refusal).split(' — ', 1)[-1]}")
    return found


def _declared(meta: Path) -> tuple[dict[str, list[tuple[str, str, str]]], list[str]]:
    """-> (code -> [(holder, statement, section)], the author's defects named). More than
    one holder for a code = a double. ADOPTED contracts declare too: an offered skill's
    laws enter the registry -- one code, one holder, wherever the holder lives."""
    import os
    found: dict[str, list[tuple[str, str, str]]] = {}
    warnings: list[str] = []
    adopted = [(contract, os.path.relpath(contract, meta))
               for _, _, contract in _adopted_offers(meta)] if instance.is_instance(meta) else []
    for path, shown in ([(one, str(one.relative_to(meta))) for one in _swept(meta)] + adopted):
        try:
            document = reading.read(path)
        except Refusal as refusal:
            if refusal.code.startswith("front-matter"):
                continue      # no front matter, so nothing declared -- a fact, not a fault
            raise
        for sign, code, text, section in _deltas(meta, document, shown, warnings):
            if sign == "+":
                found.setdefault(code, []).append((shown, text, section))
    return found, warnings


def declarations(meta: Path) -> dict[str, list[tuple[str, str, str]]]:
    return _declared(meta)[0]


def _doubles(meta: Path, found: dict[str, list[tuple[str, str, str]]]
             ) -> tuple[dict[str, list], dict[str, list]]:
    """-> (what refuses, what warns) among the codes declared twice: a double the AUTHOR
    holds warns and its first declaration stands, one held between PACKAGES refuses."""
    doubled = {code: holders for code, holders in found.items() if len(holders) > 1}
    refusing = {code: holders for code, holders in doubled.items()
                if not any(authored(meta, one) for one, _, _ in holders)}
    return refusing, {code: holders for code, holders in doubled.items() if code not in refusing}


def _orphans(meta: Path) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """-> (what refuses, what warns) among the attaches no proc hooks: the AUTHOR's
    attach warns, a package's refuses."""
    hooks, attaches = _hooks_and_attaches(meta)
    orphaned = {name: holders for name, holders in attaches.items() if name not in hooks}
    refusing = {name: holders for name, holders in orphaned.items()
                if not any(authored(meta, one) for one in holders)}
    return refusing, {name: holders for name, holders in orphaned.items() if name not in refusing}


def _kept(found: dict[str, list[tuple[str, str, str]]]) -> dict[str, tuple[str, str, str]]:
    """-> one holder per code, the FIRST in sweep order -- what the registries render
    when a double the author holds was warned about rather than refused."""
    return {code: holders[0] for code, holders in found.items()}


def _hooks_and_attaches(meta: Path) -> tuple[set[str], dict[str, list[str]]]:
    """-> (every hook DECLARED in a reachable proc, socket -> [holders]) -- a holder
    names its socket by either entry verb, `attach:` or `mount:`: one socket, one list."""
    hooks: set[str] = set()
    attaches: dict[str, list[str]] = {}
    for path in _swept(meta):
        front = _front(path)
        if front is None:
            continue
        for line in front.get("proc", "").splitlines():
            words = line.split()
            if len(words) == 2 and words[0] == "HOOK":
                hooks.add(words[1])
        for key in ("attach", "mount"):
            for name in str(front.get(key, "")).split():
                attaches.setdefault(name, []).append(str(path.relative_to(meta)))
    return hooks, attaches


def lint(meta: Path) -> list[str]:
    """-> WARNINGS (never refusals): design smells the build points at, and the law
    defects of the AUTHOR's own documents -- a code declared twice, a line out of form,
    an attach no proc hooks. The same defect in a PACKAGE refuses at the registry: the
    product answers for itself, the author is told."""
    warnings = []
    found, malformed = _declared(meta)
    warnings.extend(malformed)
    _, doubled = _doubles(meta, found)
    for code, holders in sorted(doubled.items()):
        warnings.append(f"constraint-doubled: `{code}` declared by "
                        f"{', '.join(one for one, _, _ in holders)} -- the first is kept")
    _, orphaned = _orphans(meta)
    for name, holders in sorted(orphaned.items()):
        warnings.append(f"attach-unhooked: `{name}` attached by {', '.join(holders)} -- "
                        "no proc declares that HOOK")
    declared = meta / "SYSTEM_PROMPT.md"
    if declared.is_file():
        front = _front(declared)
        if front is None or not reading.truthy(front.get("override")):
            warnings.append("SYSTEM_PROMPT.md is present but does not declare "
                            "`override: true` -- it has NO effect")
    for name, _, path in entries(meta):
        if name in RESERVED:
            warnings.append(f"skill-shadows-verb: `{name}` ({path}) takes a console "
                            f"verb's name -- unreachable through `pp {name}`, rename it")
    if instance.is_instance(meta):
        for name in _declared_names(meta):
            contract = instance.adopted(meta, name)
            if contract is not None:
                lacking = conductible(contract)
                if lacking:
                    warnings.append(f"offered-not-conductible: `{name}` ({contract}) -- "
                                    f"{lacking}; offered name-only, nothing conducted")
    for path in _swept(meta):
        # a flow lives at a kind the engine PLAYS; anywhere else a `proc:` is an
        # authoring slip -- the mount ignores it, and the KIND says so without
        # naming a directory
        front = _front(path)
        if (front is not None and str(front.get("proc", "")).strip()
                and str(front.get("kind", "")).strip() not in PLAYED):
            warnings.append(f"{path.relative_to(meta)}: carries a `proc:` but its `kind` is "
                            f"`{front.get('kind') or 'unsaid'}` -- a flow lives at "
                            f"{' or '.join(PLAYED)}, and a mount ignores it elsewhere")
    return warnings


def render_registry(meta: Path) -> str:
    """-> the derived constraints table -- the allocation CONTROL and an inspection
    surface: it refuses a doubled code and an unhooked attach, and is rendered on
    demand, never written to disk (the constraints build left with batch
    le-registre-aux-codes)."""
    found, _ = _declared(meta)
    doubled, _ = _doubles(meta, found)
    if doubled:
        raise Refusal("constraint-doubled",
                      " · ".join(f"`{code}` declared by {', '.join(h for h, _, _ in holders)}"
                                 for code, holders in doubled.items()))
    orphaned, _ = _orphans(meta)
    if orphaned:
        raise Refusal("attach-unhooked",
                      " · ".join(f"`{name}` attached by {', '.join(holders)} -- no proc "
                                 "declares that HOOK" for name, holders in orphaned.items()))
    rows = "".join(f"| `{code}` | {section} | `{holder}` | {text} |\n"
                   for code, (holder, text, section) in sorted(_kept(found).items()))
    return REGISTRY + (rows or "| — | — | — | no constraint declared |\n")


def build_system(meta: Path) -> Path | None:
    """The MARBLE, compiled: `.sys/system.md` aggregates every SYSTEM fragment --
    each package's `system/*.md` bodies, the kit's first (pin order), name order
    within a package -- into the standing rules an adapter may pin into a host's
    system prompt; pp itself only ever APPENDS them. `SYSTEM_PROMPT.md` at the
    instance root -- operator-authored, never seeded -- composes
    `.sys/system.replace.md` (its body first, the marble appended) under its own
    `override: true`; absent or not true, the replace artifact is RETRACTED."""
    fragments = []
    for root in instance.vendored(meta):
        for path in sorted((root / "system").glob("*.md")):
            fragments.append(
                reading.body_of(reading.served(path)[0]).strip())
        card = root / "refs" / "PP.md"
        if root.name.startswith(f"{instance.base_of(meta)}@") and card.is_file():
            # the agent contract comes with the marble: envelope first, the canonical
            # card next, the other packages' laws after -- ONE compiled ADN
            fragments.append(
                reading.body_of(reading.served(card)[0]).strip())
    if not fragments:
        return None                    # a kit-less instance carries no marble
    body = "\n\n".join(fragments)
    target = meta / instance.SYS / "system.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body + "\n", encoding="utf-8")
    _record_receipt(meta, target)
    replace = meta / instance.SYS / "system.replace.md"
    declared = meta / "SYSTEM_PROMPT.md"
    front = _front(declared) if declared.is_file() else None
    if front is not None and reading.truthy(front.get("override")):
        own = reading.body_of(declared.read_text(encoding="utf-8")).strip()
        replace.write_text(own + "\n\n" + body + "\n", encoding="utf-8")
    elif replace.exists():             # the lock retracts what it no longer grants
        replace.unlink()
    return target


